input {
  tcp {
    port => 5000
    codec => json
  }
}

filter {
  if [type] == "service-logs" {
    mutate {
      add_tag => [ "service" ]
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "it-ops-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}