quarkus.application.name=events-alarms-service
quarkus.application.version=1.0.0
quarkus.http.port=8081
quarkus.package.type=uber-jar
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/itops
quarkus.hibernate-orm.database.generation=update
quarkus.log.level=INFO
quarkus.log.category."com.itops".level=DEBUG